

<MenuWidget>:
    # MenuWidget hérite de relativelayout - par conséquent les propriétés sont celles
    # d'un Layout et pas d'un Widget
    # effet de fond noir lors de l'affichage du menu
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0.8
            # noir à 80% visible (20% transparent)
        Rectangle:
            size: self.size
    Label:
        font_name: "RESSOURCES/fonts/Sackers-Gothic-Std-Light.ttf"
        font_size: dp(50)
        text: root.parent.menu_title # cette variable s'adapte dans main.py selon l'état du jeu
        pos_hint: {"center_x": .5, "center_y": .6}
    Button:
        text: root.parent.menu_button_title # cette variable s'adapte dams main.py selon l'état du jeu
        font_name: "RESSOURCES/fonts/Eurostile.ttf"
        font_size: dp(20)
        pos_hint: {"center_x": .5, "center_y": .3}
        size_hint: .2, .15
        on_press: root.parent.on_menu_button_pressed() # root.parent = le MainWidget
        # root = MenuWidget > le parent du MenuWidget est le MainWidget
        background_normal: '' # empêche que la couleur grise par défaut soient multipliées par la couleur de fond ci-dessous
        background_color: 1, .3, .4, .85 # couleur de fond du bouton

