<test@BoxLayout>:





                BoxLayout:
                    orientation: "vertical"
                    RelativeLayout:
                        canvas:
                            Color:
                                rgb: 0, 0, 0.6
                            Rectangle:
                                size: self.size
                    RelativeLayout:
                        canvas:
                            Color:
                                rgb: 0, 0.6, 0
                            Rectangle:
                                size: self.size